import type { OverworldRegion } from './overworldTypes';

/** Region 3 — dark dunes beneath the eclipse horizon. */
export const BLACK_ECLIPSE_RIM: OverworldRegion = {
  id: 'black-eclipse-rim',
  name: 'Black Eclipse Rim',
  subtitle: 'Iron vanguard · sunless sky · the last gate',
  width: 1800,
  height: 1400,
  defaultSpawn: { x: 220, y: 720 },
  theme: {
    baseColor: 0x3a3344,
    accentColor: 0x2a2233,
    title: 'Black Eclipse Rim',
  },
  walls: [
    { x: 0, y: 0, w: 1800, h: 24 },
    { x: 0, y: 1376, w: 1800, h: 24 },
    { x: 0, y: 0, w: 24, h: 1400 },
    { x: 1776, y: 0, w: 24, h: 1400 },
  ],
  transitions: [
    {
      id: 'transition-to-scorpion-valley',
      x: 0,
      y: 620,
      w: 90,
      h: 180,
      label: '← Return to Scorpion Valley',
      targetRegionId: 'scorpion-valley',
      targetX: 1860,
      targetY: 900,
    },
  ],
  pois: [
    {
      id: 'poi-eclipse-outpost',
      kind: 'camp_hub',
      x: 340,
      y: 720,
      radius: 120,
      label: 'Eclipse Outpost',
      fastTravel: true,
    },
    {
      id: 'poi-black-eclipse-gate',
      kind: 'mission',
      x: 980,
      y: 680,
      radius: 100,
      label: 'Black Eclipse Gate',
      missionId: 'mission-black-eclipse',
      unlockAfterMission: 'mission-shrine-sanctum',
    },
    {
      id: 'poi-eclipse-scout',
      kind: 'npc',
      x: 420,
      y: 660,
      radius: 55,
      label: 'Sentinel Scout',
      npcId: 'eclipse_scout',
    },
    {
      id: 'poi-eclipse-omen',
      kind: 'event',
      x: 720,
      y: 520,
      radius: 70,
      label: 'Eclipse Omen',
      eventId: 'eclipse_omen',
      chestGold: 25,
      eventLoreId: 'lore-black-eclipse',
    },
    {
      id: 'poi-shadow-fortress',
      kind: 'locked_gate',
      x: 1480,
      y: 640,
      radius: 85,
      label: 'Shadow Emir Fortress',
      missionId: 'mission-shadow-emir',
      unlockAfterMission: 'mission-black-eclipse',
      revealAfterMission: 'mission-black-eclipse',
    },
  ],
  patrols: [
    {
      id: 'patrol-eclipse-wraiths',
      label: 'Sand Wraith Pack',
      texture: 'sand_bandit',
      path: [
        { x: 860, y: 780 },
        { x: 980, y: 720 },
        { x: 1100, y: 780 },
        { x: 980, y: 840 },
      ],
      speed: 60,
      touchRadius: 42,
      missionId: 'mission-black-eclipse',
      ambushBrief: 'Wraiths drift through the eclipse shadow. Cut through and reach the gate before the vanguard arrives.',
      revealAfterMission: 'mission-shrine-sanctum',
    },
  ],
};
