import type { OverworldRegion } from './overworldTypes';

export const DRYING_WELL: OverworldRegion = {
  id: 'drying-well',
  name: 'Nahran Village',
  subtitle: 'The Drying Well · village, palms, oasis road, and bandit camp',
  width: 2200,
  height: 1700,
  defaultSpawn: { x: 460, y: 1320 },
  theme: {
    baseColor: 0xc9a75d,
    accentColor: 0xb98c55,
    title: 'The Drying Well',
  },
  walls: [
    { x: 0, y: 0, w: 2200, h: 24 },
    { x: 0, y: 1676, w: 2200, h: 24 },
    { x: 0, y: 0, w: 24, h: 1700 },
    { x: 2176, y: 0, w: 24, h: 1700 },
    { x: 840, y: 980, w: 90, h: 260 },
    { x: 1330, y: 800, w: 90, h: 260 },
  ],
  pois: [
    { id: 'poi-malik-camp', kind: 'camp_hub', x: 460, y: 1320, radius: 135, label: 'Malik\'s Camp', fastTravel: true },
    { id: 'poi-nahran-village', kind: 'event', x: 620, y: 1180, radius: 90, label: 'Nahran Village', eventId: 'inspect_well', objectiveId: 'inspect_well' },
    { id: 'poi-village-elder', kind: 'npc', x: 560, y: 1120, radius: 60, label: 'Village Elder', npcId: 'village_elder', questId: 'quest-drying-well' },
    { id: 'poi-blacksmith-demo', kind: 'npc', x: 410, y: 1220, radius: 58, label: 'Blacksmith', npcId: 'demo_blacksmith', questId: 'quest-blacksmith-ore' },
    { id: 'poi-herbalist-demo', kind: 'npc', x: 740, y: 1220, radius: 58, label: 'Herbalist', npcId: 'demo_herbalist', questId: 'quest-herbalist-medicine' },
    { id: 'poi-hunter-demo', kind: 'npc', x: 360, y: 1050, radius: 58, label: 'Hunter', npcId: 'demo_hunter', questId: 'quest-hunters-lesson' },
    { id: 'poi-fisherman-demo', kind: 'npc', x: 1120, y: 540, radius: 58, label: 'Fisherman', npcId: 'demo_fisherman', questId: 'quest-fisherman-first-catch' },
    { id: 'poi-merchant-demo', kind: 'npc', x: 700, y: 1320, radius: 58, label: 'Merchant', npcId: 'demo_merchant' },
    { id: 'poi-injured-guard', kind: 'npc', x: 1030, y: 900, radius: 58, label: 'Injured Guard', npcId: 'injured_guard', questId: 'quest-road-trouble' },
    {
      id: 'poi-palm-grove',
      kind: 'gather',
      x: 360,
      y: 780,
      radius: 85,
      label: 'Palm Grove',
      itemRewards: { palm_wood: 3, dry_wood: 2, rope: 1 },
    },
    {
      id: 'poi-herb-patch',
      kind: 'gather',
      x: 920,
      y: 700,
      radius: 85,
      label: 'Oasis Herbs',
      itemRewards: { healing_herb: 3, desert_mint: 1 },
      objectiveId: 'healing_herb',
    },
    {
      id: 'poi-village-well',
      kind: 'gather',
      x: 650,
      y: 1080,
      radius: 65,
      label: 'Village Well',
      itemRewards: { water_flask: 2 },
      objectiveId: 'water_sample',
    },
    {
      id: 'poi-stone-ridge',
      kind: 'gather',
      x: 1480,
      y: 610,
      radius: 80,
      label: 'Stone Ridge',
      itemRewards: { stone: 5, iron_ore: 2 },
      objectiveId: 'stone',
    },
    {
      id: 'poi-small-cave',
      kind: 'gather',
      x: 1740,
      y: 500,
      radius: 90,
      label: 'Small Cave',
      itemRewards: { iron_ore: 3, stone: 2, relic_shard: 1 },
      requiredItemId: 'torch',
      objectiveId: 'iron_ore',
    },
    {
      id: 'poi-small-oasis',
      kind: 'fishing',
      x: 1120,
      y: 600,
      radius: 95,
      label: 'Small Oasis',
      itemRewards: { small_oasis_fish: 1 },
      objectiveId: 'small_oasis_fish',
      fastTravel: true,
    },
    {
      id: 'poi-hare-trail',
      kind: 'hunt',
      x: 720,
      y: 740,
      radius: 80,
      label: 'Hare Trail',
      itemRewards: { raw_meat: 1, hide: 1 },
      objectiveId: 'hunt_hare',
    },
    {
      id: 'poi-hyena-road',
      kind: 'combat',
      x: 1180,
      y: 900,
      radius: 85,
      label: 'Hyena Road',
      enemyType: 'hyena',
      enemyHp: 35,
      itemRewards: { hide: 1, feather: 1 },
      objectiveId: 'defeat_hyena',
    },
    {
      id: 'poi-broken-cart-demo',
      kind: 'event',
      x: 1360,
      y: 940,
      radius: 80,
      label: 'Broken Cart',
      eventId: 'broken_cart_demo',
      objectiveId: 'reach_broken_cart',
      itemRewards: { feather: 2, rope: 1 },
    },
    {
      id: 'poi-bandit-footprints',
      kind: 'event',
      x: 1540,
      y: 920,
      radius: 70,
      label: 'Bandit Footprints',
      eventId: 'bandit_footprints',
      objectiveId: 'track_footprints',
    },
    {
      id: 'poi-bandit-camp',
      kind: 'combat',
      x: 1760,
      y: 920,
      radius: 95,
      label: 'Bandit Camp',
      enemyType: 'bandit',
      enemyHp: 55,
      itemRewards: { arrows: 5 },
      goldReward: 15,
      objectiveId: 'defeat_bandit',
    },
    {
      id: 'poi-rashid-boss',
      kind: 'boss',
      x: 1940,
      y: 900,
      radius: 105,
      label: 'Bandit Captain Rashid',
      enemyType: 'rashid',
      enemyHp: 130,
      itemRewards: { stolen_water_tools: 1 },
      goldReward: 40,
      objectiveId: 'defeat_rashid',
    },
  ],
};
