import type { OverworldRegion } from './overworldTypes';

export const DRYING_WELL: OverworldRegion = {
  id: 'drying-well',
  name: 'Nahran Village',
  subtitle: 'The Drying Well · village, palms, oasis road, and bandit camp',
  width: 2200,
  height: 2300,
  defaultSpawn: { x: 1100, y: 1240 },
  theme: {
    baseColor: 0xc9a75d,
    accentColor: 0xb98c55,
    title: 'The Drying Well',
  },
  walls: [
    { x: 0, y: 0, w: 2200, h: 24 },
    { x: 0, y: 2276, w: 2200, h: 24 },
    { x: 0, y: 0, w: 24, h: 2300 },
    { x: 2176, y: 0, w: 24, h: 2300 },
    // Natural gates create clear paths without making a huge open field.
    { x: 720, y: 650, w: 120, h: 250 },
    { x: 1360, y: 650, w: 120, h: 250 },
    { x: 770, y: 1500, w: 100, h: 250 },
    { x: 1280, y: 1520, w: 90, h: 220 },
    { x: 1420, y: 2030, w: 130, h: 170 },
    { x: 1800, y: 2030, w: 130, h: 170 },
  ],
  pois: [
    { id: 'poi-malik-camp', kind: 'camp_hub', x: 1100, y: 1240, radius: 120, label: 'Malik\'s Camp', fastTravel: true },
    { id: 'poi-camp-storage', kind: 'event', x: 1020, y: 1220, radius: 45, label: 'Storage Chest', eventId: 'camp_storage', itemRewards: { dates: 2, rope: 1 } },
    { id: 'poi-campfire', kind: 'event', x: 1170, y: 1260, radius: 45, label: 'Campfire', eventId: 'campfire', itemRewards: { grilled_fish: 1 } },
    { id: 'poi-camp-signpost', kind: 'event', x: 1110, y: 1090, radius: 45, label: 'Village Signpost', eventId: 'village_signpost' },

    { id: 'poi-nahran-village', kind: 'event', x: 1100, y: 850, radius: 90, label: 'Central Well', eventId: 'inspect_well', objectiveId: 'inspect_well' },
    { id: 'poi-village-elder', kind: 'npc', x: 1110, y: 730, radius: 60, label: 'Village Elder', npcId: 'village_elder', questId: 'quest-drying-well' },
    { id: 'poi-blacksmith-demo', kind: 'npc', x: 860, y: 850, radius: 58, label: 'Blacksmith', npcId: 'demo_blacksmith', questId: 'quest-blacksmith-ore' },
    { id: 'poi-herbalist-demo', kind: 'npc', x: 1350, y: 850, radius: 58, label: 'Herbalist', npcId: 'demo_herbalist', questId: 'quest-herbalist-medicine' },
    { id: 'poi-hunter-demo', kind: 'npc', x: 900, y: 690, radius: 58, label: 'Hunter', npcId: 'demo_hunter', questId: 'quest-hunters-lesson' },
    { id: 'poi-fisherman-demo', kind: 'npc', x: 620, y: 560, radius: 58, label: 'Fisherman', npcId: 'demo_fisherman', questId: 'quest-fisherman-first-catch' },
    { id: 'poi-merchant-demo', kind: 'npc', x: 1220, y: 960, radius: 58, label: 'Merchant', npcId: 'demo_merchant' },
    { id: 'poi-child-demo', kind: 'npc', x: 980, y: 950, radius: 44, label: 'Village Child', npcId: 'demo_child' },
    { id: 'poi-water-carrier-demo', kind: 'npc', x: 1210, y: 780, radius: 44, label: 'Water Carrier', npcId: 'demo_water_carrier' },
    { id: 'poi-date-farmer-demo', kind: 'npc', x: 1030, y: 620, radius: 44, label: 'Date Farmer', npcId: 'demo_date_farmer' },
    { id: 'poi-village-guard-demo', kind: 'npc', x: 1120, y: 1020, radius: 44, label: 'Village Guard', npcId: 'demo_village_guard' },
    { id: 'poi-camp-cook-demo', kind: 'npc', x: 1180, y: 1180, radius: 44, label: 'Camp Cook', npcId: 'demo_camp_cook' },
    { id: 'poi-herbalist-free-potion', kind: 'event', x: 1410, y: 800, radius: 42, label: 'Herbalist Gift', eventId: 'herbalist_free_potion', itemRewards: { healing_potion: 1 } },
    { id: 'poi-blacksmith-cache', kind: 'event', x: 790, y: 920, radius: 45, label: 'Blacksmith Cache', eventId: 'blacksmith_cache', itemRewards: { stone: 2, iron_ore: 1 } },
    { id: 'poi-lost-toy', kind: 'event', x: 980, y: 1030, radius: 45, label: 'Lost Toy', eventId: 'lost_toy', itemRewards: { thread: 1 }, goldReward: 5 },
    { id: 'poi-hidden-herb-pot', kind: 'event', x: 1420, y: 920, radius: 45, label: 'Hidden Herb Pot', eventId: 'hidden_herb_pot', itemRewards: { healing_herb: 2 } },
    { id: 'poi-old-well-note', kind: 'event', x: 1040, y: 830, radius: 45, label: 'Old Well Note', eventId: 'old_well_note', itemRewards: { recipe_healing_potion: 1 } },

    {
      id: 'poi-palm-grove',
      kind: 'gather',
      x: 1100,
      y: 500,
      radius: 85,
      label: 'Palm Grove Main',
      itemRewards: { palm_wood: 10, dry_wood: 6, dates: 3, rope: 1, thread: 1 },
    },
    {
      id: 'poi-palm-grove-deep',
      kind: 'gather',
      x: 1080,
      y: 320,
      radius: 75,
      label: 'Palm Grove Deep',
      itemRewards: { palm_wood: 5, healing_herb: 2, dates: 2 },
    },
    {
      id: 'poi-herb-patch',
      kind: 'gather',
      x: 760,
      y: 430,
      radius: 85,
      label: 'Rare Herb Spot',
      itemRewards: { healing_herb: 6, desert_mint: 2 },
      objectiveId: 'healing_herb',
    },
    {
      id: 'poi-hidden-shrine',
      kind: 'event',
      x: 1110,
      y: 150,
      radius: 58,
      label: 'Hidden Shrine',
      eventId: 'hidden_shrine',
      itemRewards: { relic_shard: 1, desert_mint: 1 },
      goldReward: 20,
    },
    {
      id: 'poi-grove-secret-chest',
      kind: 'event',
      x: 910,
      y: 280,
      radius: 48,
      label: 'Palm-Covered Chest',
      eventId: 'grove_secret_chest',
      itemRewards: { healing_herb: 2, recipe_grilled_fish: 1 },
      goldReward: 20,
    },
    {
      id: 'poi-village-well',
      kind: 'gather',
      x: 1140,
      y: 840,
      radius: 65,
      label: 'Village Well',
      itemRewards: { water_flask: 4 },
      objectiveId: 'water_sample',
    },
    {
      id: 'poi-stone-ridge',
      kind: 'gather',
      x: 1540,
      y: 500,
      radius: 80,
      label: 'Rocky Edge',
      itemRewards: { stone: 8, iron_ore: 2 },
      objectiveId: 'stone',
    },
    {
      id: 'poi-small-cave',
      kind: 'gather',
      x: 1650,
      y: 620,
      radius: 90,
      label: 'Small Cave',
      itemRewards: { iron_ore: 4, stone: 5, relic_shard: 1 },
      requiredItemId: 'torch',
      objectiveId: 'iron_ore',
    },
    {
      id: 'poi-cave-cracked-wall',
      kind: 'event',
      x: 1770,
      y: 520,
      radius: 55,
      label: 'Cracked Cave Wall',
      eventId: 'cave_cracked_wall',
      requiredItemId: 'pickaxe',
      itemRewards: { iron_ore: 3, relic_shard: 1, recipe_simple_spear: 1 },
      goldReward: 25,
    },
    {
      id: 'poi-small-oasis',
      kind: 'fishing',
      x: 620,
      y: 580,
      radius: 95,
      label: 'Small Oasis Dock',
      itemRewards: { small_oasis_fish: 2 },
      objectiveId: 'small_oasis_fish',
      fastTravel: true,
    },
    {
      id: 'poi-oasis-reeds',
      kind: 'fishing',
      x: 500,
      y: 470,
      radius: 70,
      label: 'Reed Fishing Spot',
      itemRewards: { small_oasis_fish: 2, salt: 1 },
      objectiveId: 'small_oasis_fish',
    },
    {
      id: 'poi-rare-fishing-spot',
      kind: 'fishing',
      x: 420,
      y: 650,
      radius: 60,
      label: 'Rare Fishing Spot',
      itemRewards: { rare_oasis_fish: 1, small_oasis_fish: 1 },
      objectiveId: 'small_oasis_fish',
    },
    {
      id: 'poi-oasis-water-jars',
      kind: 'gather',
      x: 690,
      y: 700,
      radius: 55,
      label: 'Water Jars',
      itemRewards: { water_flask: 3, healing_herb: 1 },
    },
    {
      id: 'poi-hare-trail',
      kind: 'hunt',
      x: 1260,
      y: 420,
      radius: 80,
      label: 'Hare Trail',
      itemRewards: { raw_meat: 2, hide: 2, feather: 1 },
      objectiveId: 'hunt_hare',
      objectiveAmount: 2,
    },
    {
      id: 'poi-scorpion-burrow',
      kind: 'combat',
      x: 1520,
      y: 720,
      radius: 78,
      label: 'Scorpion Burrow',
      enemyType: 'scorpion',
      enemyHp: 15,
      itemRewards: { salt: 1, stone: 1 },
    },
    {
      id: 'poi-hyena-road',
      kind: 'combat',
      x: 1090,
      y: 1520,
      radius: 85,
      label: 'Hyena Road',
      enemyType: 'hyena',
      enemyHp: 25,
      enemyCount: 3,
      itemRewards: { hide: 1, feather: 1 },
      objectiveId: 'defeat_hyena',
      objectiveAmount: 3,
    },
    {
      id: 'poi-injured-guard',
      kind: 'npc',
      x: 1080,
      y: 1430,
      radius: 58,
      label: 'Injured Guard',
      npcId: 'injured_guard',
      questId: 'quest-road-trouble',
    },
    {
      id: 'poi-broken-cart-demo',
      kind: 'event',
      x: 1110,
      y: 1460,
      radius: 80,
      label: 'Broken Cart',
      eventId: 'broken_cart_demo',
      objectiveId: 'reach_broken_cart',
      itemRewards: { feather: 2, rope: 1, arrows: 5 },
    },
    {
      id: 'poi-road-warning-sign',
      kind: 'event',
      x: 1070,
      y: 1370,
      radius: 45,
      label: 'Broken Sign',
      eventId: 'road_warning_sign',
      itemRewards: { thread: 1 },
    },
    {
      id: 'poi-side-loot-cache',
      kind: 'event',
      x: 650,
      y: 1620,
      radius: 65,
      label: 'Side Loot Cache',
      eventId: 'side_loot_cache',
      itemRewards: { iron_ore: 3, healing_herb: 2, bait: 2 },
      goldReward: 35,
    },
    {
      id: 'poi-side-path-archer',
      kind: 'combat',
      x: 770,
      y: 1580,
      radius: 80,
      label: 'Side Path Archer',
      enemyType: 'bandit_archer',
      enemyHp: 25,
      enemyCount: 1,
      itemRewards: { arrows: 8, recipe_arrows: 1 },
      goldReward: 12,
      objectiveId: 'defeat_bandit',
      objectiveAmount: 1,
    },
    {
      id: 'poi-side-path-scorpion',
      kind: 'combat',
      x: 610,
      y: 1540,
      radius: 70,
      label: 'Loot Path Scorpion',
      enemyType: 'scorpion',
      enemyHp: 15,
      itemRewards: { salt: 1, stone: 2 },
    },
    {
      id: 'poi-bandit-footprints',
      kind: 'event',
      x: 1310,
      y: 1610,
      radius: 70,
      label: 'Bandit Footprints',
      eventId: 'bandit_footprints',
      objectiveId: 'track_footprints',
    },
    {
      id: 'poi-bandit-trail-shortcut',
      kind: 'event',
      x: 1400,
      y: 1680,
      radius: 65,
      label: 'Bandit Trail Shortcut',
      eventId: 'bandit_trail_shortcut',
      itemRewards: { rope: 1 },
      fastTravel: true,
    },
    {
      id: 'poi-bandit-camp',
      kind: 'combat',
      x: 1510,
      y: 1900,
      radius: 95,
      label: 'Outer Bandit Camp',
      enemyType: 'bandit',
      enemyHp: 35,
      enemyCount: 2,
      itemRewards: { arrows: 5 },
      goldReward: 15,
      objectiveId: 'defeat_bandit',
      objectiveAmount: 2,
    },
    {
      id: 'poi-bandit-archer',
      kind: 'combat',
      x: 1690,
      y: 1840,
      radius: 82,
      label: 'Bandit Lookout',
      enemyType: 'bandit_archer',
      enemyHp: 25,
      enemyCount: 1,
      itemRewards: { arrows: 8, thread: 1 },
      goldReward: 10,
      objectiveId: 'defeat_bandit',
      objectiveAmount: 1,
    },
    {
      id: 'poi-prisoner-cage',
      kind: 'event',
      x: 1430,
      y: 2010,
      radius: 58,
      label: 'Prisoner Cage',
      eventId: 'prisoner_cage',
      itemRewards: { healing_potion: 1 },
      goldReward: 10,
    },
    {
      id: 'poi-bandit-storage',
      kind: 'event',
      x: 1800,
      y: 1980,
      radius: 58,
      label: 'Stolen Storage',
      eventId: 'bandit_storage',
      itemRewards: { water_flask: 3, iron_ore: 2, hide: 1 },
      goldReward: 25,
    },
    {
      id: 'poi-rashid-boss',
      kind: 'boss',
      x: 1620,
      y: 2130,
      radius: 105,
      label: 'Bandit Captain Rashid',
      enemyType: 'rashid',
      enemyHp: 180,
      itemRewards: { stolen_water_tools: 1 },
      goldReward: 40,
      objectiveId: 'defeat_rashid',
    },
    {
      id: 'poi-oasis-road',
      kind: 'locked_gate',
      x: 1620,
      y: 2230,
      radius: 80,
      label: 'Road to Next Region',
      unlockAfterDemoUnlock: 'oasis_road',
      revealAfterDemoUnlock: 'oasis_road',
      fastTravel: true,
    },
  ],
};
