import type { OverworldRegion } from './overworldTypes';

/** Region 1 — explorable Nahran Outskirts (top-down RPG layer). */
export const NAHRAN_OUTSKIRTS: OverworldRegion = {
  id: 'nahran-outskirts',
  name: 'Nahran Outskirts',
  subtitle: 'Warm dunes · camp fires · the road to the oasis',
  width: 2200,
  height: 1700,
  defaultSpawn: { x: 520, y: 1280 },
  walls: [
    // Map edge only — walk freely across the open desert
    { x: 0, y: 0, w: 2200, h: 24 },
    { x: 0, y: 1676, w: 2200, h: 24 },
    { x: 0, y: 0, w: 24, h: 1700 },
    { x: 2176, y: 0, w: 24, h: 1700 },
    // Red Dune Pass — narrow gate bar when locked
    { x: 1220, y: 1500, w: 160, h: 36 },
  ],
  pois: [
    {
      id: 'poi-nahran-camp',
      kind: 'camp_hub',
      x: 480,
      y: 1240,
      radius: 140,
      label: 'Nahran Camp',
      fastTravel: true,
    },
    {
      id: 'poi-nahran-gate',
      kind: 'mission',
      x: 920,
      y: 1180,
      radius: 90,
      label: 'Nahran Gate',
      missionId: 'mission-night-attack',
    },
    {
      id: 'poi-scout',
      kind: 'npc',
      x: 560,
      y: 1160,
      radius: 55,
      label: 'Old Scout',
      npcId: 'old_scout',
    },
    {
      id: 'poi-blacksmith',
      kind: 'npc',
      x: 400,
      y: 1300,
      radius: 55,
      label: 'Blacksmith',
      npcId: 'blacksmith',
    },
    {
      id: 'poi-broken-cart',
      kind: 'event',
      x: 780,
      y: 980,
      radius: 60,
      label: 'Broken Caravan',
      eventId: 'broken_caravan',
    },
    {
      id: 'poi-hyena-tracks',
      kind: 'event',
      x: 680,
      y: 1060,
      radius: 55,
      label: 'Hyena Tracks',
      eventId: 'hyena_tracks',
      chestGold: 20,
      eventLoreId: 'lore-hyena-tracks',
      revealAfterMission: 'mission-night-attack',
    },
    {
      id: 'poi-hidden-chest',
      kind: 'chest',
      x: 180,
      y: 760,
      radius: 50,
      label: 'Hidden Cache',
      chestGold: 40,
      chestIron: 1,
    },
    {
      id: 'poi-hidden-cave',
      kind: 'resource',
      x: 220,
      y: 620,
      radius: 70,
      label: 'Hidden Cave',
      resourceLocationId: 'wood-grove',
      revealAfterMission: 'mission-night-attack',
    },
    {
      id: 'poi-silent-oasis',
      kind: 'mission',
      x: 1100,
      y: 520,
      radius: 100,
      label: 'Silent Oasis',
      missionId: 'mission-silent-oasis',
      revealAfterMission: 'mission-night-attack',
      fastTravel: true,
    },
    {
      id: 'poi-water-keeper',
      kind: 'npc',
      x: 1180,
      y: 480,
      radius: 55,
      label: 'Water Keeper',
      npcId: 'water_keeper',
      revealAfterMission: 'mission-night-attack',
    },
    {
      id: 'poi-bandit-road',
      kind: 'ambush',
      x: 1580,
      y: 900,
      radius: 80,
      label: 'Bandit Road',
      missionId: 'mission-bandit-road',
      revealAfterMission: 'mission-night-attack',
    },
    {
      id: 'poi-broken-watchtower',
      kind: 'mission',
      x: 1100,
      y: 200,
      radius: 90,
      label: 'Broken Watchtower',
      missionId: 'mission-broken-watchtower',
      revealAfterMission: 'mission-red-dune-pass',
    },
    {
      id: 'poi-red-dune-gate',
      kind: 'locked_gate',
      x: 1280,
      y: 1520,
      radius: 70,
      label: 'Red Dune Pass',
      missionId: 'mission-red-dune-pass',
      unlockAfterMission: 'mission-silent-oasis',
    },
  ],
  patrols: [
    {
      id: 'patrol-gate-hyenas',
      label: 'Hyena Pack',
      texture: 'hyena',
      path: [
        { x: 820, y: 1210 },
        { x: 900, y: 1160 },
        { x: 980, y: 1210 },
        { x: 900, y: 1260 },
      ],
      speed: 65,
      touchRadius: 44,
      missionId: 'mission-night-attack',
      ambushBrief: 'Hyenas prowl the road to the gate. Cut through and reach the eastern watch before dawn.',
      disableAfterMission: 'mission-night-attack',
    },
    {
      id: 'patrol-bandit-road',
      label: 'Bandit Patrol',
      texture: 'sand_bandit',
      path: [
        { x: 1360, y: 940 },
        { x: 1520, y: 900 },
        { x: 1680, y: 920 },
        { x: 1520, y: 960 },
      ],
      speed: 50,
      touchRadius: 40,
      missionId: 'mission-bandit-road',
      ambushBrief: 'Bandits spotted you on the trade road. Fight through the ambush or flee and return prepared.',
      revealAfterMission: 'mission-night-attack',
      disableAfterMission: 'mission-bandit-road',
    },
  ],
};

export const OVERWORLD_REGIONS: Record<string, OverworldRegion> = {
  'nahran-outskirts': NAHRAN_OUTSKIRTS,
};

export function getOverworldRegion(id: string): OverworldRegion {
  return OVERWORLD_REGIONS[id] ?? NAHRAN_OUTSKIRTS;
}
