import type { OverworldRegion } from './overworldTypes';

/** Region 2 — rocky canyon and scorpion hunting grounds. */
export const SCORPION_VALLEY: OverworldRegion = {
  id: 'scorpion-valley',
  name: 'Scorpion Valley',
  subtitle: 'Poison pools · iron mines · the nest below',
  width: 2000,
  height: 1600,
  defaultSpawn: { x: 600, y: 140 },
  theme: {
    baseColor: 0x8b7355,
    accentColor: 0x6b5344,
    title: 'Scorpion Valley',
  },
  walls: [
    { x: 0, y: 0, w: 2000, h: 24 },
    { x: 0, y: 1576, w: 2000, h: 24 },
    { x: 0, y: 0, w: 24, h: 1600 },
    { x: 1976, y: 0, w: 24, h: 1600 },
    // Poison pool hazards (visual blockers)
    { x: 880, y: 720, w: 120, h: 80 },
    { x: 420, y: 980, w: 100, h: 70 },
  ],
  transitions: [
    {
      id: 'transition-to-nahran',
      x: 480,
      y: 0,
      w: 280,
      h: 100,
      label: 'Red Dune Pass → Nahran Outskirts',
      targetRegionId: 'nahran-outskirts',
      targetX: 1300,
      targetY: 1510,
    },
    {
      id: 'transition-to-eclipse-rim',
      x: 1880,
      y: 820,
      w: 100,
      h: 160,
      label: 'Enter Black Eclipse Rim',
      targetRegionId: 'black-eclipse-rim',
      targetX: 220,
      targetY: 720,
      unlockAfterMission: 'mission-shrine-sanctum',
    },
  ],
  pois: [
    {
      id: 'poi-valley-camp',
      kind: 'camp_hub',
      x: 620,
      y: 280,
      radius: 120,
      label: 'Valley Camp',
      fastTravel: true,
    },
    {
      id: 'poi-scorpion-nest',
      kind: 'mission',
      x: 980,
      y: 1180,
      radius: 100,
      label: 'Scorpion Nest',
      missionId: 'mission-scorpion-nest',
    },
    {
      id: 'poi-valley-trapper',
      kind: 'npc',
      x: 540,
      y: 320,
      radius: 55,
      label: 'Hamza the Fire Trapper',
      npcId: 'hamza_trapper',
    },
    {
      id: 'poi-iron-mine',
      kind: 'resource',
      x: 320,
      y: 640,
      radius: 70,
      label: 'Iron Mine',
      resourceLocationId: 'iron-vein',
    },
    {
      id: 'poi-poison-pools',
      kind: 'event',
      x: 940,
      y: 760,
      radius: 65,
      label: 'Poison Pools',
      eventId: 'poison_pools',
      chestGold: 15,
      eventLoreId: 'lore-scorpion-nest',
    },
    {
      id: 'poi-sentinel-gate',
      kind: 'locked_gate',
      x: 1680,
      y: 820,
      radius: 75,
      label: 'Sentinel Road',
      missionId: 'mission-broken-watchtower',
      unlockAfterMission: 'mission-scorpion-nest',
      revealAfterMission: 'mission-scorpion-nest',
    },
    {
      id: 'poi-sentinel-shrine',
      kind: 'mission',
      x: 1820,
      y: 960,
      radius: 85,
      label: 'Shrine of the First Sentinels',
      missionId: 'mission-shrine-sanctum',
      revealAfterMission: 'mission-broken-watchtower',
      unlockAfterMission: 'mission-broken-watchtower',
    },
  ],
  patrols: [
    {
      id: 'patrol-valley-scorpions',
      label: 'Scorpion Swarm',
      texture: 'hyena',
      path: [
        { x: 860, y: 1100 },
        { x: 980, y: 1050 },
        { x: 1100, y: 1100 },
        { x: 980, y: 1150 },
      ],
      speed: 55,
      touchRadius: 42,
      missionId: 'mission-scorpion-nest',
      ambushBrief: 'Scorpions boil out of the canyon sand. Clear a path to the nest entrance.',
    },
  ],
};
