import type { UpgradeDefinition } from '../types/upgrade';

export const UPGRADES: UpgradeDefinition[] = [
  {
    id: 'sword_damage',
    category: 'malik',
    name: 'Sword Level',
    description: 'Increases Malik sword damage',
    maxLevel: 10,
    baseCost: 50,
    costMultiplier: 1.5,
    effectPerLevel: 5,
  },
  {
    id: 'malik_hp',
    category: 'malik',
    name: 'Malik HP',
    description: 'Increases Malik maximum health',
    maxLevel: 10,
    baseCost: 40,
    costMultiplier: 1.4,
    effectPerLevel: 15,
  },
  {
    id: 'malik_speed',
    category: 'malik',
    name: 'Desert Agility',
    description: 'Increases Malik movement speed',
    maxLevel: 5,
    baseCost: 55,
    costMultiplier: 1.6,
    effectPerLevel: 1,
  },
  {
    id: 'block_strength',
    category: 'malik',
    name: 'Shield Mastery',
    description: 'Blocking reduces more damage',
    maxLevel: 5,
    baseCost: 65,
    costMultiplier: 1.65,
    effectPerLevel: 1,
  },
  {
    id: 'gate_hp',
    category: 'gate',
    name: 'Gate HP',
    description: 'Increases gate maximum health',
    maxLevel: 10,
    baseCost: 60,
    costMultiplier: 1.6,
    effectPerLevel: 50,
  },
  {
    id: 'repair_speed',
    category: 'gate',
    name: 'Repair Speed',
    description: 'Gate repairs faster',
    maxLevel: 5,
    baseCost: 80,
    costMultiplier: 1.8,
    effectPerLevel: 10,
  },
  {
    id: 'tower_damage',
    category: 'base',
    name: 'Tower Damage',
    description: 'Arrow towers deal more damage',
    maxLevel: 5,
    baseCost: 70,
    costMultiplier: 1.7,
    effectPerLevel: 5,
  },
  {
    id: 'sand_slash',
    category: 'malik',
    name: 'Sand Slash',
    description: 'Unlock a sweeping sand wave that hits multiple enemies',
    maxLevel: 3,
    baseCost: 150,
    costMultiplier: 2.0,
    effectPerLevel: 1,
  },
  {
    id: 'spear_level',
    category: 'malik',
    name: 'Desert Spear',
    description: 'Unlock a long-reach spear thrust for armored foes',
    maxLevel: 5,
    baseCost: 100,
    costMultiplier: 1.7,
    effectPerLevel: 5,
  },
  {
    id: 'bow_level',
    category: 'malik',
    name: 'Desert Bow',
    description: 'Unlock Malik\'s bow for ranged attacks against distant enemies',
    maxLevel: 5,
    baseCost: 100,
    costMultiplier: 1.8,
    effectPerLevel: 4,
  },
  {
    id: 'lion_level',
    category: 'lion',
    name: 'Lion Companion',
    description: 'Unlock and strengthen Sahar the desert lion',
    maxLevel: 5,
    baseCost: 120,
    costMultiplier: 2.0,
    effectPerLevel: 1,
  },
];

export function getUpgradeCost(upgrade: UpgradeDefinition, currentLevel: number): number {
  return Math.floor(upgrade.baseCost * Math.pow(upgrade.costMultiplier, currentLevel - 1));
}
