import type { EnemyDefinition } from '../types/enemy';

export const ENEMIES: Record<string, EnemyDefinition> = {
  hyena: {
    id: 'hyena',
    name: 'Hyena',
    behavior: 'melee',
    health: 30,
    damage: 8,
    speed: 120,
    attackRange: 40,
    attackCooldownMs: 1200,
    goldDrop: 5,
    xpDrop: 10,
    targetsGate: true,
  },
  sand_bandit: {
    id: 'sand_bandit',
    name: 'Sand Bandit',
    behavior: 'melee',
    health: 50,
    damage: 12,
    speed: 90,
    attackRange: 45,
    attackCooldownMs: 1500,
    goldDrop: 10,
    xpDrop: 20,
    targetsGate: true,
  },
  bandit_leader: {
    id: 'bandit_leader',
    name: 'Bandit Leader',
    behavior: 'melee',
    health: 120,
    damage: 20,
    speed: 70,
    attackRange: 50,
    attackCooldownMs: 1800,
    goldDrop: 30,
    xpDrop: 50,
    targetsGate: true,
  },
  bandit_warlord: {
    id: 'bandit_warlord',
    name: 'Bandit Warlord',
    behavior: 'boss',
    health: 280,
    damage: 28,
    speed: 55,
    attackRange: 55,
    attackCooldownMs: 1600,
    goldDrop: 80,
    xpDrop: 120,
    targetsGate: true,
    isBoss: true,
    armor: 0.15,
  },
  bandit_archer: {
    id: 'bandit_archer',
    name: 'Bandit Archer',
    behavior: 'ranged',
    health: 35,
    damage: 10,
    speed: 65,
    attackRange: 220,
    attackCooldownMs: 2000,
    goldDrop: 12,
    xpDrop: 25,
    targetsGate: true,
  },
  camel_raider: {
    id: 'camel_raider',
    name: 'Camel Raider',
    behavior: 'melee',
    health: 70,
    damage: 18,
    speed: 160,
    attackRange: 50,
    attackCooldownMs: 1400,
    goldDrop: 18,
    xpDrop: 35,
    targetsGate: true,
  },
  sand_wisp: {
    id: 'sand_wisp',
    name: 'Sand Wisp',
    behavior: 'flying',
    health: 40,
    damage: 12,
    speed: 100,
    attackRange: 180,
    attackCooldownMs: 1800,
    goldDrop: 14,
    xpDrop: 28,
    targetsGate: true,
  },
  iron_vanguard: {
    id: 'iron_vanguard',
    name: 'Iron Vanguard',
    behavior: 'melee',
    health: 150,
    damage: 15,
    speed: 45,
    attackRange: 45,
    attackCooldownMs: 2000,
    goldDrop: 25,
    xpDrop: 40,
    targetsGate: true,
    armor: 0.5,
  },
  dune_scorpion: {
    id: 'dune_scorpion',
    name: 'Dune Scorpion',
    behavior: 'melee',
    health: 200,
    damage: 25,
    speed: 50,
    attackRange: 45,
    attackCooldownMs: 2200,
    goldDrop: 50,
    xpDrop: 80,
    targetsGate: true,
    isBoss: true,
    armor: 0.2,
    poisonDps: 4,
  },
  scorpion_skitter: {
    id: 'scorpion_skitter',
    name: 'Scorpion Skitter',
    behavior: 'melee',
    health: 28,
    damage: 9,
    speed: 145,
    attackRange: 36,
    attackCooldownMs: 1000,
    goldDrop: 6,
    xpDrop: 12,
    targetsGate: true,
    poisonDps: 3,
  },
  spitting_scorpion: {
    id: 'spitting_scorpion',
    name: 'Spitting Scorpion',
    behavior: 'ranged',
    health: 45,
    damage: 11,
    speed: 55,
    attackRange: 200,
    attackCooldownMs: 2200,
    goldDrop: 14,
    xpDrop: 28,
    targetsGate: true,
    poisonDps: 5,
  },
  sand_wraith: {
    id: 'sand_wraith',
    name: 'Sand Wraith',
    behavior: 'melee',
    health: 45,
    damage: 16,
    speed: 135,
    attackRange: 38,
    attackCooldownMs: 1100,
    goldDrop: 15,
    xpDrop: 30,
    targetsGate: true,
  },
  shadow_emir: {
    id: 'shadow_emir',
    name: 'Shadow Emir',
    behavior: 'boss',
    health: 450,
    damage: 32,
    speed: 60,
    attackRange: 60,
    attackCooldownMs: 1400,
    goldDrop: 120,
    xpDrop: 200,
    targetsGate: true,
    isBoss: true,
    armor: 0.25,
  },
};

export function getEnemyDefinition(id: string): EnemyDefinition | undefined {
  return ENEMIES[id];
}

export function isBossType(enemyType: string): boolean {
  return ENEMIES[enemyType]?.isBoss === true;
}
