import type { LocationNode, MissionDefinition } from '../types/mission';

export const LOCATIONS: LocationNode[] = [
  {
    id: 'nahran-camp',
    name: 'Nahran Camp',
    description: 'The last safe camp before the desert road. Malik prepares to defend Nahran from the coming attack.',
    type: 'camp',
    biome: 'desert_night',
    difficulty: 1,
    position: { x: 20, y: 55 },
  },
  {
    id: 'night-attack',
    name: 'Night Attack on Nahran',
    description: 'The desert is quiet, but the hyenas have stopped howling. Something is coming.',
    type: 'defense',
    biome: 'desert_night',
    difficulty: 1,
    missionId: 'mission-night-attack',
    position: { x: 50, y: 45 },
  },
  {
    id: 'silent-oasis',
    name: 'Silent Oasis',
    description: 'The oasis feeds three camps. If the well falls, the desert road dies.',
    type: 'defense',
    biome: 'oasis',
    difficulty: 2,
    missionId: 'mission-silent-oasis',
    position: { x: 55, y: 55 },
    unlockRequirement: 'mission-night-attack',
  },
  {
    id: 'bandit-road',
    name: 'Bandit Road',
    description: 'A sudden ambush on the desert trail. No gate — only Malik stands between the raiders and the caravan route.',
    type: 'ambush',
    biome: 'desert_day',
    difficulty: 2,
    missionId: 'mission-bandit-road',
    position: { x: 68, y: 52 },
    unlockRequirement: 'mission-silent-oasis',
  },
  {
    id: 'dune-caravan',
    name: 'Dune Caravan Escort',
    description: 'Escort merchants across the dunes. Protect the caravan from raiders until it reaches safety.',
    type: 'defense',
    biome: 'desert_day',
    difficulty: 2,
    missionId: 'mission-caravan-escort',
    position: { x: 42, y: 62 },
    unlockRequirement: 'mission-silent-oasis',
  },
  {
    id: 'merchants-crossing',
    name: 'Merchant\'s Crossing',
    description: 'Desert traders sell rations and remedies for the road ahead.',
    type: 'shop',
    biome: 'desert_day',
    difficulty: 2,
    position: { x: 28, y: 48 },
    unlockRequirement: 'mission-red-dune-pass',
  },
  {
    id: 'hidden-cistern',
    name: 'Hidden Cistern',
    description: 'An ancient water cache buried beneath the dunes. Collect supplies once.',
    type: 'resource',
    biome: 'desert_day',
    difficulty: 2,
    loreId: 'lore-hidden-cistern',
    position: { x: 52, y: 38 },
    unlockRequirement: 'mission-caravan-escort',
  },
  {
    id: 'iron-vein',
    name: 'Red Iron Vein',
    description: 'Exposed iron ore in the red dunes. Mine it once for the camp forge.',
    type: 'resource',
    biome: 'desert_day',
    difficulty: 3,
    loreId: 'lore-iron-veins',
    position: { x: 88, y: 58 },
    unlockRequirement: 'mission-broken-watchtower',
  },
  {
    id: 'leather-cache',
    name: 'Bandit Leather Cache',
    description: 'Raider supplies hidden off the road. Claim the leather once.',
    type: 'resource',
    biome: 'desert_day',
    difficulty: 2,
    loreId: 'lore-leather-trade',
    position: { x: 74, y: 48 },
    unlockRequirement: 'mission-bandit-road',
  },
  {
    id: 'wood-grove',
    name: 'Palm Wood Grove',
    description: 'Fallen palms near the oasis — useful timber for camp defenses.',
    type: 'resource',
    biome: 'oasis',
    difficulty: 2,
    loreId: 'lore-oasis-palms',
    position: { x: 58, y: 48 },
    unlockRequirement: 'mission-silent-oasis',
  },
  {
    id: 'red-dune-pass',
    name: 'Red Dune Pass',
    description: 'The old trade road is blocked by raiders. Malik must open the path before sunrise.',
    type: 'defense',
    biome: 'desert_day',
    difficulty: 3,
    missionId: 'mission-red-dune-pass',
    position: { x: 82, y: 42 },
    unlockRequirement: 'mission-silent-oasis',
  },
  {
    id: 'broken-watchtower',
    name: 'Broken Watchtower',
    description: 'An ancient tower half-buried in sand still carries the mark of the First Sentinels.',
    type: 'boss',
    biome: 'ruins',
    difficulty: 4,
    missionId: 'mission-broken-watchtower',
    position: { x: 35, y: 30 },
    unlockRequirement: 'mission-red-dune-pass',
  },
  {
    id: 'scorpion-nest',
    name: 'Scorpion Nest',
    description: 'Green poison seeps from ancient tunnels. Defend the camp barricade from the scorpion swarm.',
    type: 'defense',
    biome: 'ruins',
    difficulty: 3,
    missionId: 'mission-scorpion-nest',
    loreId: 'lore-scorpion-nest',
    position: { x: 48, y: 18 },
    unlockRequirement: 'mission-broken-watchtower',
  },
  {
    id: 'sentinel-shrine',
    name: 'Shrine of the First Sentinels',
    description: 'Sacred stones mark the resting place of the desert\'s first guardians.',
    type: 'lore',
    biome: 'ruins',
    difficulty: 3,
    loreId: 'lore-first-sentinels',
    position: { x: 72, y: 58 },
    unlockRequirement: 'mission-red-dune-pass',
  },
  {
    id: 'shrine-sanctum',
    name: 'Shrine Sanctum',
    description: 'Defend the sacred shrine as enemies attack from both sides of the ruins.',
    type: 'defense',
    biome: 'ruins',
    difficulty: 3,
    missionId: 'mission-shrine-sanctum',
    position: { x: 60, y: 65 },
    unlockRequirement: 'mission-red-dune-pass',
  },
  {
    id: 'black-eclipse-gate',
    name: 'Black Eclipse Gate',
    description: 'The final stand. Iron vanguards march under the eclipse.',
    type: 'boss',
    biome: 'ruins',
    difficulty: 5,
    missionId: 'mission-black-eclipse',
    position: { x: 68, y: 28 },
    unlockRequirement: 'mission-broken-watchtower',
  },
  {
    id: 'shadow-emir-fortress',
    name: 'Shadow Emir Fortress',
    description: 'Act V — The final stand. Slay the Shadow Emir and break the eclipse forever.',
    type: 'boss',
    biome: 'ruins',
    difficulty: 5,
    missionId: 'mission-shadow-emir',
    position: { x: 50, y: 22 },
    unlockRequirement: 'mission-black-eclipse',
  },
];

export const MISSIONS: MissionDefinition[] = [
  {
    id: 'mission-night-attack',
    locationId: 'night-attack',
    name: 'Night Attack on Nahran',
    description: 'Defend the camp gate from three waves of desert raiders.',
    objective: 'Protect the Nahran camp gate until sunrise.',
    storyBrief:
      'Hyenas howl in the dark dunes. Bandits follow the beasts, hoping to breach Nahran\'s gate while the city sleeps. Malik stands between the desert and his people.',
    type: 'survive',
    biome: 'desert_night',
    difficulty: 1,
    baseRewardGold: 100,
    perfectGateBonusGold: 50,
    surviveDurationMs: 72_000,
    waves: [
      {
        waveNumber: 1,
        timeBeforeWaveMs: 3000,
        rewardGold: 20,
        enemies: [{ type: 'hyena', count: 5, spawnDelayMs: 800, spawnSide: 'left' }],
      },
      {
        waveNumber: 2,
        timeBeforeWaveMs: 5000,
        rewardGold: 30,
        enemies: [
          { type: 'hyena', count: 6, spawnDelayMs: 700, spawnSide: 'left' },
          { type: 'sand_bandit', count: 2, spawnDelayMs: 1200, spawnSide: 'right' },
        ],
      },
      {
        waveNumber: 3,
        timeBeforeWaveMs: 5000,
        rewardGold: 50,
        enemies: [
          { type: 'sand_bandit', count: 3, spawnDelayMs: 900, spawnSide: 'left' },
          { type: 'sand_bandit', count: 2, spawnDelayMs: 1000, spawnSide: 'right' },
          { type: 'bandit_leader', count: 1, spawnDelayMs: 2000, spawnSide: 'right' },
        ],
      },
    ],
  },
  {
    id: 'mission-silent-oasis',
    locationId: 'silent-oasis',
    name: 'Silent Oasis',
    description: 'Protect the sacred well from a stronger raiding party.',
    objective: 'Defend the oasis well — do not let raiders destroy the water source.',
    storyBrief:
      'The Silent Oasis feeds caravans and refugees alike. Raiders know that breaking the well is faster than breaking Nahran itself. Malik must hold the line at the oasis gate.',
    type: 'oasis',
    biome: 'oasis',
    difficulty: 2,
    baseRewardGold: 150,
    perfectGateBonusGold: 75,
    unlockRequirement: 'mission-night-attack',
    waves: [
      {
        waveNumber: 1,
        timeBeforeWaveMs: 3000,
        rewardGold: 30,
        enemies: [
          { type: 'hyena', count: 4, spawnDelayMs: 600, spawnSide: 'left' },
          { type: 'sand_bandit', count: 3, spawnDelayMs: 1000, spawnSide: 'left' },
        ],
      },
      {
        waveNumber: 2,
        timeBeforeWaveMs: 5000,
        rewardGold: 40,
        enemies: [
          { type: 'sand_bandit', count: 4, spawnDelayMs: 800, spawnSide: 'right' },
          { type: 'bandit_archer', count: 2, spawnDelayMs: 1200, spawnSide: 'left' },
        ],
      },
      {
        waveNumber: 3,
        timeBeforeWaveMs: 5000,
        rewardGold: 80,
        enemies: [
          { type: 'bandit_archer', count: 3, spawnDelayMs: 800, spawnSide: 'left' },
          { type: 'scorpion_skitter', count: 4, spawnDelayMs: 600, spawnSide: 'right' },
        ],
      },
    ],
  },
  {
    id: 'mission-bandit-road',
    locationId: 'bandit-road',
    name: 'Bandit Road Ambush',
    description: 'Survive a fast ambush on the open road. Raiders strike without warning.',
    objective: 'Defeat all raiders — protect yourself and the caravan route.',
    storyBrief:
      'A merchant caravan was spotted moving through Red Dune Pass. Bandits mean to cut the road before it reaches Nahran. Malik must break the ambush alone — there is no gate to hide behind.',
    type: 'ambush',
    biome: 'desert_day',
    difficulty: 2,
    baseRewardGold: 120,
    perfectGateBonusGold: 0,
    unlockRequirement: 'mission-silent-oasis',
    waves: [
      {
        waveNumber: 1,
        timeBeforeWaveMs: 2000,
        rewardGold: 35,
        enemies: [
          { type: 'hyena', count: 4, spawnDelayMs: 500 },
          { type: 'sand_bandit', count: 3, spawnDelayMs: 700 },
        ],
      },
      {
        waveNumber: 2,
        timeBeforeWaveMs: 4000,
        rewardGold: 55,
        enemies: [
          { type: 'sand_bandit', count: 5, spawnDelayMs: 600 },
          { type: 'bandit_leader', count: 1, spawnDelayMs: 1800 },
        ],
      },
    ],
  },
  {
    id: 'mission-caravan-escort',
    locationId: 'dune-caravan',
    name: 'Dune Caravan Escort',
    description: 'Escort the trade caravan through bandit territory. Clear all waves, then reach the exit.',
    objective: 'Protect the caravan and escort it to the desert exit.',
    storyBrief:
      'Nahran\'s merchants must cross open dunes to reach the oasis trade route. Malik guards the caravan as it moves — raiders will strike from the sands while the wagons roll forward.',
    type: 'caravan',
    biome: 'desert_day',
    difficulty: 2,
    baseRewardGold: 140,
    perfectGateBonusGold: 60,
    unlockRequirement: 'mission-silent-oasis',
    waves: [
      {
        waveNumber: 1,
        timeBeforeWaveMs: 2500,
        rewardGold: 30,
        enemies: [
          { type: 'hyena', count: 4, spawnDelayMs: 600 },
          { type: 'sand_bandit', count: 2, spawnDelayMs: 900 },
        ],
      },
      {
        waveNumber: 2,
        timeBeforeWaveMs: 4500,
        rewardGold: 45,
        enemies: [
          { type: 'sand_bandit', count: 4, spawnDelayMs: 700 },
          { type: 'bandit_archer', count: 2, spawnDelayMs: 1100 },
        ],
      },
      {
        waveNumber: 3,
        timeBeforeWaveMs: 5000,
        rewardGold: 65,
        enemies: [
          { type: 'sand_bandit', count: 3, spawnDelayMs: 600 },
          { type: 'bandit_archer', count: 2, spawnDelayMs: 800 },
          { type: 'bandit_leader', count: 1, spawnDelayMs: 2000 },
        ],
      },
    ],
  },
  {
    id: 'mission-shrine-sanctum',
    locationId: 'shrine-sanctum',
    name: 'Shrine Sanctum',
    description: 'Enemies strike the sacred shrine from both sides. Hold the center at all costs.',
    objective: 'Protect the sacred shrine from raiders attacking from both directions.',
    storyBrief:
      'The First Sentinels built this shrine to anchor the desert against darkness. Raiders now strike from east and west at once, hoping to shatter the stones while Malik is caught in the middle.',
    type: 'shrine',
    biome: 'ruins',
    difficulty: 3,
    baseRewardGold: 220,
    perfectGateBonusGold: 90,
    unlockRequirement: 'mission-red-dune-pass',
    waves: [
      {
        waveNumber: 1,
        timeBeforeWaveMs: 3000,
        rewardGold: 40,
        enemies: [
          { type: 'hyena', count: 3, spawnDelayMs: 700, spawnSide: 'left' },
          { type: 'hyena', count: 3, spawnDelayMs: 700, spawnSide: 'right' },
        ],
      },
      {
        waveNumber: 2,
        timeBeforeWaveMs: 5000,
        rewardGold: 55,
        enemies: [
          { type: 'sand_bandit', count: 3, spawnDelayMs: 800, spawnSide: 'left' },
          { type: 'sand_wraith', count: 2, spawnDelayMs: 900, spawnSide: 'right' },
          { type: 'bandit_archer', count: 2, spawnDelayMs: 1200, spawnSide: 'right' },
          { type: 'sand_bandit', count: 3, spawnDelayMs: 900, spawnSide: 'right' },
        ],
      },
      {
        waveNumber: 3,
        timeBeforeWaveMs: 5000,
        rewardGold: 100,
        enemies: [
          { type: 'bandit_archer', count: 2, spawnDelayMs: 700, spawnSide: 'left' },
          { type: 'bandit_leader', count: 1, spawnDelayMs: 2000, spawnSide: 'left' },
          { type: 'sand_bandit', count: 4, spawnDelayMs: 600, spawnSide: 'right' },
          { type: 'bandit_leader', count: 1, spawnDelayMs: 2200, spawnSide: 'right' },
        ],
      },
    ],
  },
  {
    id: 'mission-red-dune-pass',
    locationId: 'red-dune-pass',
    name: 'Red Dune Pass',
    description: 'Bandit archers strike from the ridges. Build a tower and hold the gate.',
    objective: 'Hold Red Dune Pass and protect the gate from archers and raiders.',
    storyBrief:
      'Arrows fall from the crimson ridges before the bandits charge. Malik must push forward, build defenses, and keep the pass open for Nahran\'s supply lines.',
    type: 'gate_defense',
    biome: 'desert_day',
    difficulty: 3,
    baseRewardGold: 200,
    perfectGateBonusGold: 100,
    unlockRequirement: 'mission-silent-oasis',
    waves: [
      {
        waveNumber: 1,
        timeBeforeWaveMs: 3000,
        rewardGold: 40,
        enemies: [
          { type: 'hyena', count: 4, spawnDelayMs: 700 },
          { type: 'bandit_archer', count: 2, spawnDelayMs: 1500 },
        ],
      },
      {
        waveNumber: 2,
        timeBeforeWaveMs: 5000,
        rewardGold: 50,
        enemies: [
          { type: 'sand_bandit', count: 4, spawnDelayMs: 800 },
          { type: 'bandit_archer', count: 3, spawnDelayMs: 1200 },
        ],
      },
      {
        waveNumber: 3,
        timeBeforeWaveMs: 5000,
        rewardGold: 90,
        enemies: [
          { type: 'scorpion_skitter', count: 3, spawnDelayMs: 700 },
          { type: 'sand_bandit', count: 4, spawnDelayMs: 800 },
        ],
      },
      {
        waveNumber: 4,
        timeBeforeWaveMs: 6000,
        rewardGold: 110,
        enemies: [
          { type: 'bandit_leader', count: 1, spawnDelayMs: 1500 },
          { type: 'scorpion_skitter', count: 2, spawnDelayMs: 800 },
        ],
      },
    ],
  },
  {
    id: 'mission-scorpion-nest',
    locationId: 'scorpion-nest',
    name: 'Scorpion Nest',
    description: 'Poison pools spread through the rocky valley. Hold the camp barricade against the nest.',
    objective: 'Defend the camp barricade from scorpion waves — avoid the poison pools.',
    storyBrief:
      'Beneath the broken ruins, scorpions breed in green-lit tunnels. Malik must hold the supply camp barricade while poison seeps across the battlefield between each wave.',
    type: 'gate_defense',
    biome: 'ruins',
    difficulty: 3,
    baseRewardGold: 220,
    perfectGateBonusGold: 90,
    unlockRequirement: 'mission-broken-watchtower',
    requiresBossKill: 'dune_scorpion',
    waves: [
      {
        waveNumber: 1,
        timeBeforeWaveMs: 3000,
        rewardGold: 35,
        enemies: [{ type: 'scorpion_skitter', count: 6, spawnDelayMs: 500, spawnSide: 'left' }],
      },
      {
        waveNumber: 2,
        timeBeforeWaveMs: 5000,
        rewardGold: 45,
        enemies: [
          { type: 'scorpion_skitter', count: 4, spawnDelayMs: 600, spawnSide: 'right' },
          { type: 'dune_scorpion', count: 1, spawnDelayMs: 2000, spawnSide: 'left' },
        ],
      },
      {
        waveNumber: 3,
        timeBeforeWaveMs: 5000,
        rewardGold: 55,
        enemies: [
          { type: 'spitting_scorpion', count: 3, spawnDelayMs: 900, spawnSide: 'left' },
          { type: 'scorpion_skitter', count: 4, spawnDelayMs: 700, spawnSide: 'right' },
        ],
      },
      {
        waveNumber: 4,
        timeBeforeWaveMs: 6000,
        rewardGold: 95,
        enemies: [
          { type: 'spitting_scorpion', count: 2, spawnDelayMs: 800 },
          { type: 'dune_scorpion', count: 1, spawnDelayMs: 2500 },
        ],
      },
    ],
  },
  {
    id: 'mission-broken-watchtower',
    locationId: 'broken-watchtower',
    name: 'Broken Watchtower',
    description: 'Ancient ruins hide a monstrous dune scorpion. Survive the onslaught and slay the beast.',
    objective: 'Defend the watchtower gate and slay the Dune Scorpion.',
    storyBrief:
      'The broken watchtower marks the border of the First Sentinels\' old lands. Bandits stir something ancient from the sand — a dune scorpion large enough to shatter stone. Malik must survive the waves and kill the beast.',
    type: 'boss',
    biome: 'ruins',
    difficulty: 4,
    baseRewardGold: 300,
    perfectGateBonusGold: 150,
    unlockRequirement: 'mission-red-dune-pass',
    requiresBossKill: 'dune_scorpion',
    waves: [
      {
        waveNumber: 1,
        timeBeforeWaveMs: 3000,
        rewardGold: 50,
        enemies: [
          { type: 'sand_bandit', count: 4, spawnDelayMs: 800 },
          { type: 'bandit_archer', count: 2, spawnDelayMs: 1200 },
        ],
      },
      {
        waveNumber: 2,
        timeBeforeWaveMs: 5000,
        rewardGold: 60,
        enemies: [
          { type: 'bandit_leader', count: 2, spawnDelayMs: 1000 },
          { type: 'bandit_archer', count: 3, spawnDelayMs: 900 },
        ],
      },
      {
        waveNumber: 3,
        timeBeforeWaveMs: 6000,
        rewardGold: 150,
        enemies: [
          { type: 'sand_bandit', count: 4, spawnDelayMs: 700 },
          { type: 'dune_scorpion', count: 1, spawnDelayMs: 3000 },
        ],
      },
    ],
  },
  {
    id: 'mission-black-eclipse',
    locationId: 'black-eclipse-gate',
    name: 'Black Eclipse Gate',
    description: 'The desert\'s last bastion. Hold against the iron vanguard and the eclipse.',
    objective: 'Hold the final gate against the Black Eclipse assault.',
    storyBrief:
      'The sky darkens with the Black Eclipse. Iron vanguards march under a sunless horizon, and the Shadow Emir\'s host tests every defense Malik has built. This is Nahran\'s last stand.',
    type: 'boss',
    biome: 'ruins',
    difficulty: 5,
    baseRewardGold: 500,
    perfectGateBonusGold: 200,
    unlockRequirement: 'mission-broken-watchtower',
    requiresBossKill: 'bandit_warlord',
    waves: [
      {
        waveNumber: 1,
        timeBeforeWaveMs: 3000,
        rewardGold: 60,
        enemies: [
          { type: 'iron_vanguard', count: 2, spawnDelayMs: 1500 },
          { type: 'sand_wraith', count: 3, spawnDelayMs: 800 },
          { type: 'bandit_archer', count: 3, spawnDelayMs: 900 },
        ],
      },
      {
        waveNumber: 2,
        timeBeforeWaveMs: 5000,
        rewardGold: 80,
        enemies: [
          { type: 'iron_vanguard', count: 3, spawnDelayMs: 1200 },
          { type: 'bandit_leader', count: 2, spawnDelayMs: 1000 },
        ],
      },
      {
        waveNumber: 3,
        timeBeforeWaveMs: 6000,
        rewardGold: 200,
        enemies: [
          { type: 'iron_vanguard', count: 4, spawnDelayMs: 1000 },
          { type: 'bandit_warlord', count: 1, spawnDelayMs: 3500 },
          { type: 'bandit_leader', count: 2, spawnDelayMs: 800 },
        ],
      },
    ],
  },
  {
    id: 'mission-shadow-emir',
    locationId: 'shadow-emir-fortress',
    name: 'Shadow Emir\'s Fortress',
    description: 'The Shadow Emir commands the eclipse from his fortress. Slay him to save Nahran.',
    objective: 'Defeat the Shadow Emir and break the Black Eclipse.',
    storyBrief:
      'Malik returns to Nahran as the sky blackens one final time. The Shadow Emir himself waits at the fortress — every upgrade, every ally, every lesson of the desert road leads to this blade.',
    type: 'boss',
    biome: 'ruins',
    difficulty: 5,
    baseRewardGold: 600,
    perfectGateBonusGold: 250,
    unlockRequirement: 'mission-black-eclipse',
    requiresBossKill: 'shadow_emir',
    waves: [
      {
        waveNumber: 1,
        timeBeforeWaveMs: 3000,
        rewardGold: 80,
        enemies: [
          { type: 'iron_vanguard', count: 3, spawnDelayMs: 1200 },
          { type: 'sand_wisp', count: 2, spawnDelayMs: 900 },
        ],
      },
      {
        waveNumber: 2,
        timeBeforeWaveMs: 5000,
        rewardGold: 100,
        enemies: [
          { type: 'bandit_warlord', count: 1, spawnDelayMs: 2000 },
          { type: 'camel_raider', count: 3, spawnDelayMs: 700 },
          { type: 'sand_wraith', count: 3, spawnDelayMs: 600 },
        ],
      },
      {
        waveNumber: 3,
        timeBeforeWaveMs: 6000,
        rewardGold: 250,
        enemies: [
          { type: 'iron_vanguard', count: 2, spawnDelayMs: 1000 },
          { type: 'shadow_emir', count: 1, spawnDelayMs: 3500 },
        ],
      },
    ],
  },
];

export function getMissionById(id: string): MissionDefinition | undefined {
  return MISSIONS.find((m) => m.id === id);
}

export function getLocationById(id: string): LocationNode | undefined {
  return LOCATIONS.find((l) => l.id === id);
}
